name: flutter_cleaner
description: A tool to delete obsolete build folders
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.3
  macos_ui: ^1.9.1
  shared_preferences: ^2.0.17
  file_picker: ^4.6.1
  pubspec_parse: ^1.2.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
  - pubspec.yaml